coupleApp/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

coupleApp/coupleApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('trips/', include('trips.urls')),
    path('gallery/', include('gallery.urls')),
    path('makeup/', include('makeup.urls')),
    path('skincare/', include('skincare.urls')),
    path('library/', include('library.urls')),
]

coupleApp/makeup/urls.py
from django.urls import path
from . import views

app_name = 'makeup'

urlpatterns = [
    path('', views.makeup_items_page, name='makeup_items_page'),
    path('category/<str:category_name>/', views.category_items, name='category_items'),
    path('category/<str:category_name>/subcategory/<str:subcategory_name>/', views.subcategory_items, name='subcategory_items'),
    path('<int:pk>/', views.item_details_page, name='item_details_page'),
    path('new-owned-item/', views.new_owned_item, name='new_owned_item'),
    path('new-wanted-item/', views.new_wanted_item, name='new_wanted_item'),
    path('<int:pk>/edit/', views.edit_item, name='edit_item'),
    path('<int:pk>/delete/', views.delete_item, name='delete_item'),
]

coupleApp/makeup/models.py
from django.db import models
from django.forms import ValidationError

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    owned = models.BooleanField(default=False)
    brand = models.CharField(max_length=100, blank=True, null=True)

    CATEGORY_CHOICES = [
        ('Rostro', 'Rostro'),
        ('Ojos', 'Ojos'),
        ('Labios', 'Labios'),
        ('Manos', 'Manos'),
        ('Paletas', 'Paletas'),
    ]

    SUBCATEGORY_CHOICES = {
        'Rostro': [
            ('bases_maquillaje', 'Bases de maquillaje'),
            ('colorete', 'Colorete'),
            ('bronceadores', 'Bronceadores y contouring'),
            ('correctores', 'Correctores'),
            ('iluminadores', 'Iluminadores'),
            ('fijadores', 'Fijadores'),
            ('polvos', 'Polvos'),
            ('prebases_rostro', 'Prebases'),
        ],
        'Ojos': [
            ('mascaras', 'Máscaras'),
            ('sombras', 'Sombras de ojos'),
            ('lapices', 'Lápices de ojos'),
            ('cejas', 'Cejas'),
            ('delineadores', 'Delineadores'),
            ('prebases_ojos', 'Prebases para ojos'),
        ],
        'Labios': [
            ('labiales', 'Labiales'),
            ('brillos_labios', 'Brillos de labios'),
            ('lapices_contorno', 'Lápices contorno'),
            ('prebases_labios', 'Prebases para labios'),
        ],
        'Manos': [
            ('esmaltes', 'Esmaltes de uñas'),
            ('cuidado_unas', 'Cuidado de las uñas'),
            ('manicura_francesa', 'Manicura francesa'),
            ('quitaesmaltes', 'Quitaesmaltes'),
            ('fijadores_esmalte', 'Fijadores de esmalte de uñas'),
        ],
        'Paletas': [
            ('paletas_rostro', 'Paletas para rostro'),
            ('paletas_ojos', 'Paletas para ojos'),
        ],
    }

    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
    subcategory = models.CharField(max_length=50, blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    image = models.ImageField(upload_to='makeup_item_images/', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def clean(self):
        # Validación personalizada para las subcategorías
        if self.category and self.subcategory:
            valid_subcategories = dict(self.SUBCATEGORY_CHOICES).get(self.category, [])
            if not any(choice[0] == self.subcategory for choice in valid_subcategories):
                raise ValidationError({'subcategory': 'Subcategoría no válida para la categoría seleccionada.'})

    def get_subcategories(self):
        return self.SUBCATEGORY_CHOICES.get(self.category, [])

    def __str__(self):
        return self.name

coupleApp/makeup/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'owned', 'brand', 'category', 'subcategory', 'price', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Escribe el nombre'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe una descripción'}),
            'owned': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Escribe la marca'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'min': '0', 'placeholder': 'Escribe el precio'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.category:
            self.fields['subcategory'].choices = Item.SUBCATEGORY_CHOICES[self.instance.category]
        else:
            self.fields['subcategory'].choices = []

        self.fields['category'].widget.attrs.update({'onchange': 'updateSubcategories()'})

coupleApp/makeup/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from .models import Item
from .forms import ItemForm

# Create your views here.
def makeup_items_page(request):
    items = Item.objects.all().order_by('-updated_at', 'owned')
    return render(request, 'makeup_items_page.html', {'items': items})

def category_items(request, category_name):
    items = Item.objects.filter(category__iexact=category_name)  # Filtra por categoría (case-insensitive)
    return render(request, 'makeup_category_items.html', {'items': items, 'category_name': category_name})

def subcategory_items(request, category_name, subcategory_name):
    items = Item.objects.filter(category__iexact=category_name, subcategory__iexact=subcategory_name)
    return render(request, 'makeup_subcategory_items.html', {
        'items': items,
        'category_name': category_name,
        'subcategory_name': subcategory_name,
    })

def item_details_page(request, pk):
    item = get_object_or_404(Item, pk=pk)
    redirect_url = request.GET.get('redirect_to', None)
    print(redirect_url)

    return render(request, 'makeup_item_details_page.html', {'item': item, 'redirect_url': redirect_url})

def new_owned_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.owned = True 
            item.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True}, status=200)
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = ItemForm()

    return render(request, 'new_owned_item.html', {'form': form})

def new_wanted_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.owned = False
            item.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True}, status=200)
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = ItemForm()

    return render(request, 'new_wanted_item.html', {'form': form})

def edit_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('makeup:item_details_page', pk=pk)
    else:
        form = ItemForm(instance=item)
    return render(request, 'edit_makeup_item.html', {'form': form, 'item': item})

def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('makeup:makeup_items_page')
    return render(request, 'delete_confirmation.html', {'item': item})

coupleApp/makeup/templates/edit_makeup_item.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Editar producto{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <script src="{% static 'js/makeup/edit_makeup_item.js' %}" defer></script>
    <script>
        const subcategory = "{{item.subcategory}}";
    </script>
</head>
<body>
  <header class="header">
      <div class="logo-container">
          <a href="{% url 'core:home_page' %}">
            <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
          </a>
      </div>
      <div class="header-content">
          <h1>Editar producto: {{ item.name }}</h1>
      </div>
  </header>

  <div class="main-container">
    <div class="back-button-container">
      <a href="{% url 'makeup:item_details_page' item.pk%}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
    </div>
    <main class="main-content">
      <form method="post" id="dataForm" class="new-form">
        {% csrf_token %}

        <div class="form-group">
          <label for="name">Nombre</label>
          <input type="text" id="name" name="name" class="form-control" value="{{ item.name }}" required>
          <ul id="autocompleteSuggestions" class="autocomplete-suggestions"></ul>
        </div>
        
        <div class="form-group">
            <label for="description">Descripción</label>
            <textarea id="description" name="description" class="form-control">{{ item.description }}</textarea>
        </div>

        <div class="form-group">
            <label for="owned">Lo tengo</label>
            <input type="checkbox" id="owned" name="owned" class="form-control" {% if item.owned %}checked{% endif %}>
        </div>
        
        <div class="form-group">
            <label for="brand">Marca</label>
            <input type="text" id="brand" name="brand" class="form-control" value="{{item.brand}}">
        </div>

        <div class="form-group">
          <label for="category">Categoría</label>
          <select name="category" id="id_category" class="form-control" required onchange="updateSubcategories()">
            <option value="">Selecciona una categoría</option>
            <option value="Rostro" {% if item.category == "Rostro" %}selected{% endif %}>Rostro</option>
            <option value="Ojos" {% if item.category == "Ojos" %}selected{% endif %}>Ojos</option>
            <option value="Labios" {% if item.category == "Labios" %}selected{% endif %}>Labios</option>
            <option value="Manos" {% if item.category == "Manos" %}selected{% endif %}>Manos</option>
            <option value="Paletas" {% if item.category == "Paletas" %}selected{% endif %}>Paletas</option>
          </select>
        </div>

        <div class="form-group">
          <label for="subcategory">Subcategoría</label>
          <select name="subcategory" required id="id_subcategory">
            {% for subcategory in subcategories %}
            <option value="{{ subcategory.value }}" {% if subcategory.value == item.subcategory %}selected{% endif %}>{{ subcategory.label }}</option>
            {% endfor %}
          </select>
        </div>

        <div class="form-group">
            <label for="price">Precio</label>
            <input type="number" id="price" name="price" step="0.01" min="0" class="form-control" value="{{item.price}}">
        </div>

        <div class="form-group">
            <label for="image">Imagen</label>
            <input type="file" id="image" name="image" class="form-control" accept="image/*" value="{{item.image}}">
        </div>
        
        <!-- Botón de Envío -->
        <button type="submit">Guardar cambios</button>
      </form>
    </main>
  </div>

  <footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
  </footer>
</body>
</html>

coupleApp/makeup/templates/makeup_category_items.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    {% load custom_filters %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Productos de maquillaje{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/makeup/makeup_items_page.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <script src="{% static 'js/makeup/makeup_items_page.js' %}" defer></script>
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Lista de maquillaje</h1>
            <p>Aquí puedes ver todos los productos de maquillaje que tienes o quieres.</p>
        </div>
    </header>
    <nav class="makeup-desktop-menu">
        <ul class="categories">
            <li class="category">
                <a href="{% url 'makeup:category_items' 'rostro' %}">Rostro</a>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'bases_maquillaje' %}">Bases de maquillaje</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'colorete' %}">Colorete</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'bronceadores' %}">Bronceadores y contouring</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'correctores' %}">Correctores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'iluminadores' %}">Iluminadores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'fijadores' %}">Fijadores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'polvos' %}">Polvos</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'prebases_rostro' %}">Prebases</a></li>
                </ul>
            </li>
            <li class="category">
                <a href="{% url 'makeup:category_items' 'ojos' %}">Ojos</a>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'mascara' %}">Máscaras</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'sombras' %}">Sombras de ojos</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'lapices' %}">Lápices de ojos</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'cejas' %}">Cejas</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'delineadores' %}">Delineadores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'prebases_ojos' %}">Prebases para ojos</a></li>
                </ul>
            </li>
            <li class="category">
                <a href="{% url 'makeup:category_items' 'labios' %}">Labios</a>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'labiales' %}">Labiales</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'brillos_labios' %}">Brillos de labios</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'lapices_contorno' %}">Lápices contorno</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'prebases_labios' %}">Prebases para labios</a></li>
                </ul>
            </li>
            <li class="category">
                <a href="{% url 'makeup:category_items' 'manos' %}">Manos</a>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'esmaltes' %}">Esmaltes</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'cuidado_unas' %}">Cuidado de las uñas</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'manicura_francesa' %}">Manicura francesa</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'quitaesmaltes' %}">Quitaesmaltes</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'fijadores_esmalte' %}">Fijadores de esmalte de uñas</a></li>
                </ul>
            </li>
            <li class="category">
                <a href="{% url 'makeup:category_items' 'paletas' %}">Paletas</a>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:subcategory_items' 'paletas' 'paletas_rostro' %}">Paletas para rostro</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'paletas' 'paletas_ojos' %}">Paletas para ojos</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <nav class="makeup-mobile-menu">
        <button class="menu-toggle">☰ Categorías</button>
        <ul class="categories">
            <li class="category">
                <span>Rostro</span>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:category_items' 'rostro' %}">Ver todo</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'bases_maquillaje' %}">Bases de maquillaje</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'colorete' %}">Colorete</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'bronceadores' %}">Bronceadores y contouring</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'correctores' %}">Correctores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'iluminadores' %}">Iluminadores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'fijadores' %}">Fijadores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'polvos' %}">Polvos</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'rostro' 'prebases_rostro' %}">Prebases</a></li>
                </ul>
            </li>
            <li class="category">
                <span>Ojos</span>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:category_items' 'ojos' %}">Ver todo</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'mascara' %}">Máscaras</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'sombras' %}">Sombras de ojos</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'lapices' %}">Lápices de ojos</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'cejas' %}">Cejas</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'delineadores' %}">Delineadores</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'ojos' 'prebases_ojos' %}">Prebases para ojos</a></li>
                </ul>
            </li>
            <li class="category">
                <span>Labios</span>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:category_items' 'labios' %}">Ver todo</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'labiales' %}">Labiales</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'brillos_labios' %}">Brillos de labios</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'lapices_contorno' %}">Lápices contorno</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'labios' 'prebases_labios' %}">Prebases para labios</a></li>
                </ul>
            </li>
            <li class="category">
                <span>Manos</span>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:category_items' 'manos' %}">Ver todo</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'esmaltes' %}">Esmaltes</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'cuidado_unas' %}">Cuidado de las uñas</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'manicura_francesa' %}">Manicura francesa</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'quitaesmaltes' %}">Quitaesmaltes</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'manos' 'fijadores_esmalte' %}">Fijadores de esmalte de uñas</a></li>
                </ul>
            </li>
            <li class="category">
                <span>Paletas</span>
                <ul class="subcategories">
                    <li><a href="{% url 'makeup:category_items' 'paletas' %}">Ver todo</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'paletas' 'paletas_rostro' %}">Paletas para rostro</a></li>
                    <li><a href="{% url 'makeup:subcategory_items' 'paletas' 'paletas_ojos' %}">Paletas para ojos</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% url 'makeup:makeup_items_page' %}" class="btn-back">&#8592;</a>
        </div>
        <div class="add-buttons-container">
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'makeup:new_owned_item' %}" class="btn-add">
                    <button type="button">Lo tengo</button>
                </a>
            </div>
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'makeup:new_wanted_item' %}" class="btn-add">
                    <button type="button">Lo quiero</button>
                </a>
            </div>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">
            <div class="category-item-list">
                <h1 class="category-title">
                    Productos para 
                    {% if category_name == 'rostro' %}
                        el {{ category_name }}
                    {% elif category_name == 'manos' %}
                        las {{ category_name }}
                    {% else %}
                        los {{ category_name }}
                    {% endif %}
                </h1>
                
                <ul class="product-list">
                    {% for item in items %}
                        <li class="product-item">
                            <a href="{% url 'makeup:item_details_page' item.pk %}?redirect_to={% url 'makeup:category_items' category_name %}" class="product-link">
                                <div class="product-info">
                                    <h2 class="product-name">{{ item.name }}</h2>
                                    <p class="product-brand">{{ item.brand }}</p>
                                </div>
                                <span class="product-arrow">→</span>
                            </a>
                        </li>
                    {% empty %}
                        <p class="no-items">No hay ítems en esta categoría.</p>
                    {% endfor %}
                </ul>
            </div>
        </main>
    </div>
</body>
<footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
</footer>
</html>

coupleApp/makeup/templates/makeup_item_details_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    {% load custom_filters %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}Detalles del producto{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Detalles del producto</h1>
        </div>
    </header>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% if redirect_url %}
                        {{ redirect_url }}
                     {% else %}
                        {% url 'makeup:all_items_page' %}
                     {% endif %}" 
            class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">
            <div class="details">
                <header class="details-header">
                    <div class="action-buttons">
                        <a href="{% url 'makeup:edit_item' item.pk %}" class="btn-edit"><i class="fas fa-pencil-alt"></i></a>
                        <form action="{% url 'makeup:delete_item' item.pk %}" method="post" class="btn-delete-form">
                            {% csrf_token %}
                            <button type="submit" class="btn-delete" onclick="return confirm('¿Estás seguro de que deseas eliminar este producto?')"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </div>
                    <h2>{{ item.name }}</h2>
                </header>
        
                <section class="description">
                    <h3>Descripción</h3>
                    <p>{{ item.description }}</p>
                </section>
                
                <section class="item-info">
                    <h3>Información adicional</h3>
                    <ul>
                        <li><strong>Marca:</strong> {{ item.brand|default:"No disponible" }}</li>
                        <li><strong>Categoría:</strong> {{ item.category|default:"No disponible" }}</li>
                        <li><strong>Sub-categoría:</strong> {{ item.subcategory|subcategory_label|default:"No disponible" }}</li>
                        <li><strong>Precio:</strong> {% if item.price %}{{ item.price }} €{% else %}No disponible{% endif %}</li>
                        <li><strong>Lo tengo:</strong> 
                            {% if item.owned %}
                                <i class="fas fa-check-circle" style="color: green;"></i> Sí
                            {% else %}
                                <i class="fas fa-times-circle" style="color: red;"></i> No
                            {% endif %}
                        </li>
                    </ul>
                </section>

                <section class="item-image">
                    <h3>Imagen del Producto</h3>
                    {% if item.image %}
                        <img src="{{ item.image.url }}" alt="Imagen de {{ item.name }}" class="item-image-preview">
                    {% else %}
                        <p>No se ha cargado imagen.</p>
                    {% endif %}
                </section>

                <section class="updated-at">
                    <h3>Última actualización</h3>
                    <p>{{ item.updated_at }}</p>
                </section>

            </div>
        </main>
    </div>
    <footer class="footer">
        <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
    </footer>
</body>
</html>