coupleApp/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

coupleApp/coupleApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('trips/', include('trips.urls')),
    path('gallery/', include('gallery.urls')),
    path('makeup/', include('makeup.urls')),
    path('skincare/', include('skincare.urls')),
    path('library/', include('library.urls')),
]

coupleApp/gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.photo_gallery, name='photo_gallery'),
]

coupleApp/library/urls.py
from django.urls import path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.library_page, name='library_page'),
    path('<int:pk>/', views.book_details_page, name='book_details_page'),
    path('new-book/', views.new_book, name='new_book'),
    path('<int:pk>/edit/', views.edit_book, name='edit_book'),
    path('<int:pk>/delete/', views.delete_book, name='delete_book'),
]

coupleApp/makeup/urls.py
from django.urls import path
from . import views

app_name = 'makeup'

urlpatterns = [
    path('', views.makeup_items_page, name='makeup_items_page'),
    path('category/<str:category_name>/', views.category_items, name='category_items'),
    path('category/<str:category_name>/subcategory/<str:subcategory_name>/', views.subcategory_items, name='subcategory_items'),
    path('<int:pk>/', views.item_details_page, name='item_details_page'),
    path('new-owned-item/', views.new_owned_item, name='new_owned_item'),
    path('new-wanted-item/', views.new_wanted_item, name='new_wanted_item'),
    path('<int:pk>/edit/', views.edit_item, name='edit_item'),
    path('<int:pk>/delete/', views.delete_item, name='delete_item'),
]

coupleApp/trips/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'trips'  # Namespace para la aplicación 'trips'

urlpatterns = [
    path('', views.trips_page, name='trips_page'),
    path('<int:pk>/', views.trip_details_page, name='trip_details_page'),
    path('mapa-datos/', views.trips_geojson, name='trips_geojson'),
    path('new-trip/', views.new_trip, name='new_trip'),
    path('<int:pk>/edit/', views.edit_trip, name='edit_trip'),
    path('<int:pk>/delete/', views.delete_trip, name='delete_trip'),
    path('<int:pk>/add-photos/', views.add_trip_photos, name='add_trip_photos'),
    path('delete-photo/<int:photo_id>/', views.delete_trip_photo, name='delete_trip_photo'),
    path('get-google-maps-key/', views.get_google_maps_key, name='get_google_maps_key'),
]

if settings.DEBUG:  # Solo para el entorno de desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupleApp/core/models.py
from django.db import models

# Create your models here.

coupleApp/core/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
    return render(request, 'home_page.html')

coupleApp/core/templates/home_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lucier Home</title>
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/core/home_page.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">
</head>
<body>
    <!-- Header section with only the image -->
    <header class="header">
        <div class="home-logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static '/images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
    </header>
    <!-- Main container section for all pages -->
    <div class="main-container">
        <!-- Main Navigation Menu -->
        <nav class="home-menu">
            <ul>
                <li><a href="{% url 'trips:trips_page' %}" class="home-menu-item">Sitios en donde hemos estado</a></li>
                <li><a href="{% url 'gallery:photo_gallery' %}" class="home-menu-item">Galería de Fotos</a></li>
                <li><a href="{% url 'makeup:makeup_items_page' %}" class="home-menu-item">Mi maquillaje</a></li>
                <li><a href="{% url 'skincare:skincare_products_page' %}" class="home-menu-item">Mi skincare</a></li>
                <li><a href="{% url 'library:library_page' %}" class="home-menu-item">Mi librería</a></li>
                <li><a href="#" class="home-menu-item">Próximamente: Nuevas Aplicaciones</a></li>
            </ul>
        </nav>

        <!-- Footer section -->
        <footer class="footer">
            <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
        </footer>
    </div>
</body>
</html>