coupleApp/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

coupleApp/coupleApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('trips/', include('trips.urls')),
    path('gallery/', include('gallery.urls')),
    path('makeup/', include('makeup.urls')),
    path('skincare/', include('skincare.urls')),
    path('library/', include('library.urls')),
]

coupleApp/skincare/urls.py
from django.urls import path
from . import views

app_name = 'skincare'

urlpatterns = [
    path('', views.skincare_products_page, name='skincare_products_page'),
    path('category/<str:category_name>/', views.category_products, name='category_products'),
    path('<int:pk>/', views.skincare_product_details_page, name='skincare_product_details_page'),
    path('new-owned-skincare-product/', views.new_owned_skincare_product, name='new_owned_skincare_product'),
    path('new-wanted-skincare-product/', views.new_wanted_skincare_product, name='new_wanted_skincare_product'),
    path('<int:pk>/edit/', views.edit_skincare_product, name='edit_skincare_product'),
    path('<int:pk>/delete/', views.delete_skincare_product, name='delete_skincare_product'),
]

coupleApp/skincare/models.py
from django.db import models
from django.forms import ValidationError

# Create your models here.
class SkincareProduct(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    owned = models.BooleanField(default=False)
    brand = models.CharField(max_length=100, blank=True, null=True)

    CATEGORY_CHOICES = [
        ('Limpiadores', 'Limpiadores'),
        ('Tonicos', 'Tónicos'),
        ('Serums', 'Serums'),
        ('Crema_hidratante', 'Crema hidratante'),
        ('Contorno_de_ojos', 'Contorno de ojos'),
        ('Exfoliantes', 'Exfoliantes'),
        ('Tratamiento_de_labios', 'Tratamiento de labios'),
        ('Desmaquillantes', 'Desmaquillantes'),
        ('Mascarillas', 'Mascarillas'),
    ]

    category = models.CharField(max_length=21, choices=CATEGORY_CHOICES)

    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    image = models.ImageField(upload_to='skincare_product_images/', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return self.name

coupleApp/skincare/forms.py
from django import forms

from .models import SkincareProduct

class SkincareProductForm(forms.ModelForm):
    class Meta:
        model = SkincareProduct
        fields = ['name', 'description', 'owned', 'brand', 'category', 'price', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Escribe el nombre'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe una descripción'}),
            'owned': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Escribe la marca'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'min': '0', 'placeholder': 'Escribe el precio'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

coupleApp/skincare/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from .models import SkincareProduct
from .forms import SkincareProductForm

# Create your views here.
def skincare_products_page(request):
    skincare_products = SkincareProduct.objects.all().order_by('-updated_at', 'owned')
    return render(request, 'skincare_products_page.html', {'skincare_products': skincare_products})

def category_products(request, category_name):
    skincare_products = SkincareProduct.objects.filter(category__iexact=category_name)  # Filtra por categoría (case-insensitive)
    return render(request, 'skincare_category_products.html', {'skincare_products': skincare_products, 'category_name': category_name})

def skincare_product_details_page(request, pk):
    skincare_product = get_object_or_404(SkincareProduct, pk=pk)
    redirect_url = request.GET.get('redirect_to', None)
    print(redirect_url)

    return render(request, 'skincare_product_details_page.html', {'skincare_product': skincare_product, 'redirect_url': redirect_url})

def new_owned_skincare_product(request):
    if request.method == 'POST':
        form = SkincareProductForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.owned = True 
            item.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True}, status=200)
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = SkincareProductForm()

    return render(request, 'new_owned_skincare_product.html', {'form': form})

def new_wanted_skincare_product(request):
    if request.method == 'POST':
        form = SkincareProductForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.owned = False
            item.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True}, status=200)
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = SkincareProductForm()

    return render(request, 'new_wanted_skincare_product.html', {'form': form})

def edit_skincare_product(request, pk):
    skincare_product = get_object_or_404(SkincareProduct, pk=pk)
    if request.method == 'POST':
        form = SkincareProductForm(request.POST, instance=skincare_product)
        if form.is_valid():
            form.save()
            return redirect('makeup:item_details_page', pk=pk)
    else:
        form = SkincareProductForm(instance=skincare_product)
    return render(request, 'edit_skincare_product.html', {'form': form, 'skincare_product': skincare_product})

def delete_skincare_product(request, pk):
    skincare_product = get_object_or_404(SkincareProduct, pk=pk)
    if request.method == 'POST':
        skincare_product.delete()
        return redirect('skincare:skincare_products_page')
    return render(request, 'delete_confirmation.html', {'skincare_product': skincare_product})

coupleApp/skincare/templates/edit_skincare_product.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Editar producto de skincare{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <script src="{% static 'js/skincare/edit_skincare_product.js' %}" defer></script>
</head>
<body>
  <header class="header">
      <div class="logo-container">
          <a href="{% url 'core:home_page' %}">
            <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
          </a>
      </div>
      <div class="header-content">
          <h1>Editar producto de skincare: {{ skincare_product.name }}</h1>
      </div>
  </header>

  <div class="main-container">
    <div class="back-button-container">
      <a href="{% url 'skincare:skincare_product_details_page' item.pk%}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
    </div>
    <main class="main-content">
      <form method="post" id="dataForm" class="new-form">
        {% csrf_token %}

        <div class="form-group">
          <label for="name">Nombre</label>
          <input type="text" id="name" name="name" class="form-control" value="{{ skincare_product.name }}" required>
          <ul id="autocompleteSuggestions" class="autocomplete-suggestions"></ul>
        </div>
        
        <div class="form-group">
            <label for="description">Descripción</label>
            <textarea id="description" name="description" class="form-control">{{ skincare_product.description }}</textarea>
        </div>

        <div class="form-group">
            <label for="owned">Lo tengo</label>
            <input type="checkbox" id="owned" name="owned" class="form-control" {% if skincare_product.owned %}checked{% endif %}>
        </div>
        
        <div class="form-group">
            <label for="brand">Marca</label>
            <input type="text" id="brand" name="brand" class="form-control" value="{{skincare_product.brand}}">
        </div>

        <div class="form-group">
          <label for="category">Categoría</label>
          <select name="category" id="id_category" class="form-control" required>
            <option value="">Selecciona una categoría</option>
            <option value="Rostro" {% if item.category == "Rostro" %}selected{% endif %}>Rostro</option>
            <option value="Ojos" {% if item.category == "Ojos" %}selected{% endif %}>Ojos</option>
            <option value="Labios" {% if item.category == "Labios" %}selected{% endif %}>Labios</option>
            <option value="Manos" {% if item.category == "Manos" %}selected{% endif %}>Manos</option>
            <option value="Paletas" {% if item.category == "Paletas" %}selected{% endif %}>Paletas</option>
          </select>
        </div>

        <div class="form-group">
            <label for="price">Precio</label>
            <input type="number" id="price" name="price" step="0.01" min="0" class="form-control" value="{{skincare_product.price}}">
        </div>

        <div class="form-group">
            <label for="image">Imagen</label>
            <input type="file" id="image" name="image" class="form-control" accept="image/*" value="{{skincare_product.image}}">
        </div>
        
        <!-- Botón de Envío -->
        <button type="submit">Guardar cambios</button>
      </form>
    </main>
  </div>

  <footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
  </footer>
</body>
</html>

coupleApp/skincare/templates/skincare_category_products.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    {% load custom_filters %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Productos de skincare{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/makeup/makeup_items_page.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <script src="{% static 'js/skincare/skincare_products_page.js' %}" defer></script>
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Lista de skincare</h1>
            <p>Aquí puedes ver todos los productos de skincare que tienes o quieres.</p>
        </div>
    </header>
    <nav class="makeup-desktop-menu">
        <ul class="categories">
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Limpiadores' %}">Limpiadores</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tonicos' %}">Tónicos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Serums' %}">Serums</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Crema_hidratante' %}">Crema hidratante</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Contorno_de_ojos' %}">Contorno de ojos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Exfoliantes' %}">Exfoliantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tratamiento_de_labios' %}">Tratamiento de labios</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Desmaquillantes' %}">Desmaquillantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Mascarillas' %}">Mascarillas</a>
            </li>
        </ul>
    </nav>
    <nav class="makeup-mobile-menu">
        <button class="menu-toggle">☰ Categorías</button>
        <ul class="categories">
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Limpiadores' %}">Limpiadores</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tonicos' %}">Tónicos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Serums' %}">Serums</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Crema_hidratante' %}">Crema hidratante</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Contorno_de_ojos' %}">Contorno de ojos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Exfoliantes' %}">Exfoliantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tratamiento_de_labios' %}">Tratamiento de labios</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Desmaquillantes' %}">Desmaquillantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Limpiadores' %}">Limpiadores</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Mascarillas' %}">Mascarillas</a>
            </li>
        </ul>
    </nav>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% url 'skincare:skincare_products_page' %}" class="btn-back">&#8592;</a>
        </div>
        <div class="add-buttons-container">
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'skincare:new_owned_skincare_product' %}" class="btn-add">
                    <button type="button">Lo tengo</button>
                </a>
            </div>
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'skincare:new_wanted_skincare_product' %}" class="btn-add">
                    <button type="button">Lo quiero</button>
                </a>
            </div>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">
            <div class="category-item-list">
                <h1 class="category-title">
                    {{ category_name }}
                </h1>
                
                <ul class="product-list">
                    {% for skincare_product in skincare_products %}
                        <li class="product-item">
                            <a href="{% url 'skincare:skincare_product_details_page' skincare_product.pk %}?redirect_to={% url 'skincare:category_products' category_name %}" class="product-link">
                                <div class="product-info">
                                    <h2 class="product-name">{{ skincare_product.name }}</h2>
                                    <p class="product-brand">{{ skincare_product.brand }}</p>
                                </div>
                                <span class="product-arrow">→</span>
                            </a>
                        </li>
                    {% empty %}
                        <p class="no-items">No hay productos en esta categoría.</p>
                    {% endfor %}
                </ul>
            </div>
        </main>
    </div>
</body>
<footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
</footer>
</html>

coupleApp/skincare/templates/skincare_product_details_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    {% load custom_filters %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}Detalles del producto{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Detalles del producto</h1>
        </div>
    </header>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% if redirect_url %}
                        {{ redirect_url }}
                     {% else %}
                        {% url 'skincare:skincare_products_page' %}
                     {% endif %}" 
            class="btn-back" aria-label="Volver a la lista de productos">&#8592;</a>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">
            <div class="details">
                <header class="details-header">
                    <div class="action-buttons">
                        <a href="{% url 'skincare:edit_skincare_product' skincare_product.pk %}" class="btn-edit"><i class="fas fa-pencil-alt"></i></a>
                        <form action="{% url 'skincare:delete_skincare_product' skincare_product.pk %}" method="post" class="btn-delete-form">
                            {% csrf_token %}
                            <button type="submit" class="btn-delete" onclick="return confirm('¿Estás seguro de que deseas eliminar este producto?')"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </div>
                    <h2>{{ skincare_product.name }}</h2>
                </header>
        
                <section class="description">
                    <h3>Descripción</h3>
                    <p>{{ skincare_product.description }}</p>
                </section>
                
                <section class="item-info">
                    <h3>Información adicional</h3>
                    <ul>
                        <li><strong>Marca:</strong> {{ skincare_product.brand|default:"No disponible" }}</li>
                        <li><strong>Categoría:</strong> {{ skincare_product.category|default:"No disponible" }}</li>
                        <li><strong>Precio:</strong> {% if skincare_product.price %}{{ skincare_product.price }} €{% else %}No disponible{% endif %}</li>
                        <li><strong>Lo tengo:</strong> 
                            {% if skincare_product.owned %}
                                <i class="fas fa-check-circle" style="color: green;"></i> Sí
                            {% else %}
                                <i class="fas fa-times-circle" style="color: red;"></i> No
                            {% endif %}
                        </li>
                    </ul>
                </section>

                <section class="item-image">
                    <h3>Imagen del Producto</h3>
                    {% if skincare_product.image %}
                        <img src="{{ skincare_product.image.url }}" alt="Imagen de {{ skincare_product.name }}" class="item-image-preview">
                    {% else %}
                        <p>No se ha cargado imagen.</p>
                    {% endif %}
                </section>

                <section class="updated-at">
                    <h3>Última actualización</h3>
                    <p>{{ skincare_product.updated_at }}</p>
                </section>

            </div>
        </main>
    </div>
    <footer class="footer">
        <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
    </footer>
</body>
</html>

coupleApp/skincare/templates/skincare_products_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    {% load custom_filters %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Productos de skincare{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/makeup/makeup_items_page.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <script src="{% static 'js/skincare/skincare_products_page.js' %}" defer></script>
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Lista de skincare</h1>
            <p>Aquí puedes ver todos los productos de skincare que tienes o quieres.</p>
        </div>
    </header>
    <nav class="makeup-desktop-menu">
        <ul class="categories">
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Limpiadores' %}">Limpiadores</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tonicos' %}">Tónicos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Serums' %}">Serums</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Crema_hidratante' %}">Crema hidratante</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Contorno_de_ojos' %}">Contorno de ojos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Exfoliantes' %}">Exfoliantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tratamiento_de_labios' %}">Tratamiento de labios</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Desmaquillantes' %}">Desmaquillantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Mascarillas' %}">Mascarillas</a>
            </li>
        </ul>
    </nav>
    <nav class="makeup-mobile-menu">
        <button class="menu-toggle">☰ Categorías</button>
        <ul class="categories">
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Limpiadores' %}">Limpiadores</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tonicos' %}">Tónicos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Serums' %}">Serums</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Crema_hidratante' %}">Crema hidratante</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Contorno_de_ojos' %}">Contorno de ojos</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Exfoliantes' %}">Exfoliantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Tratamiento_de_labios' %}">Tratamiento de labios</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Desmaquillantes' %}">Desmaquillantes</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Limpiadores' %}">Limpiadores</a>
            </li>
            <li class="category">
                <a href="{% url 'skincare:category_products' 'Mascarillas' %}">Mascarillas</a>
            </li>
        </ul>
    </nav>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% url 'core:home_page' %}" class="btn-back">&#8592;</a>
        </div>
        <div class="add-buttons-container">
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'skincare:new_owned_skincare_product' %}" class="btn-add">
                    <button type="button">Lo tengo</button>
                </a>
            </div>
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'skincare:new_wanted_skincare_product' %}" class="btn-add">
                    <button type="button">Lo quiero</button>
                </a>
            </div>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">
            <div class="responsive-table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Marca</th>
                            <th class="desktop-only">Categoría</th>
                            <th class="desktop-only">Descripción</th>
                            <th class="desktop-only">Lo tengo</th>
                            <th>Detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for skincare_product in skincare_products %}
                        <tr>
                            <td>{{ skincare_product.name }}</td>
                            <td>{{ skincare_product.brand }}</td>
                            <td class="desktop-only">{{ skincare_product.category}}</td>
                            <td class="desktop-only">{{ skincare_product.description|default:"Sin descripción" }}</td>
                            <td class="desktop-only" style="text-align: center;">
                                {% if skincare_product.owned %}
                                    <i class="fas fa-check" style="color: green;"></i> <!-- Tick -->
                                {% else %}
                                    <i class="fas fa-times" style="color: red;"></i> <!-- Cruz -->
                                {% endif %}
                            </td>
                            <td style="text-align: center;">
                                <a href="{% url 'skincare:skincare_product_details_page' skincare_product.pk %}?redirect_to={% url 'skincare:skincare_products_page' %}" class="btn-details">
                                    <i class="fas fa-eye"></i> <!-- Icono de ojo -->
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6">No hay productos disponibles.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</body>
<footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
</footer>
</html>