coupleApp/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

coupleApp/coupleApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('trips/', include('trips.urls')),
    path('gallery/', include('gallery.urls')),
    path('makeup/', include('makeup.urls')),
    path('skincare/', include('skincare.urls')),
    path('library/', include('library.urls')),
]

coupleApp/trips/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'trips'  # Namespace para la aplicación 'trips'

urlpatterns = [
    path('', views.trips_page, name='trips_page'),
    path('<int:pk>/', views.trip_details_page, name='trip_details_page'),
    path('mapa-datos/', views.trips_geojson, name='trips_geojson'),
    path('new-trip/', views.new_trip, name='new_trip'),
    path('<int:pk>/edit/', views.edit_trip, name='edit_trip'),
    path('<int:pk>/delete/', views.delete_trip, name='delete_trip'),
    path('<int:pk>/add-photos/', views.add_trip_photos, name='add_trip_photos'),
    path('delete-photo/<int:photo_id>/', views.delete_trip_photo, name='delete_trip_photo'),
    path('get-google-maps-key/', views.get_google_maps_key, name='get_google_maps_key'),
]

if settings.DEBUG:  # Solo para el entorno de desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupleApp/trips/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Trip(models.Model):
    destiny = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.destiny
    
    def time_interval(self):
        return f"From {self.start_date} to {self.end_date}"
    
    def clean(self):
        if self.end_date < self.start_date:
            raise ValidationError('The ending date cannot be before the starting date.')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

coupleApp/trips/forms.py
from django import forms

from .models import Trip

class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['destiny', 'description', 'start_date', 'end_date', 'latitude', 'longitude']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
            'latitude': forms.TextInput(attrs={'readonly': 'readonly'}),
            'longitude': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

coupleApp/trips/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.core.exceptions import ValidationError
from django.conf import settings

from .models import Trip
from gallery.models import Photo
from .forms import TripForm

import os

# Create your views here.
def trips_page(request):
    trips = Trip.objects.all()
    return render(request, 'trips_page.html', {'trips': trips})

def trip_details_page(request, pk):
    trip = get_object_or_404(Trip, pk=pk)
    return render(request, 'trip_details_page.html', {'trip': trip})

def trips_geojson(request):
    trips = Trip.objects.all()
    features = []

    for trip in trips:
        features.append({
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [trip.longitude, trip.latitude]
            },
            "properties": {
                "destiny": trip.destiny,
                "description": trip.description,
                "pk": trip.pk
            }
        })

    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    return JsonResponse(geojson)

def get_google_maps_key(request):
    return JsonResponse({'apiKey': settings.GOOGLE_MAPS_API_KEY})

def new_trip(request):
    if request.method == 'POST':
        form = TripForm(request.POST)
        if form.is_valid():
            form.save()  # Guarda el nuevo sitio en la base de datos
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True}, status=200)
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = TripForm()

    return render(request, 'new_trip.html', {'form': form})

def edit_trip(request, pk):
    trip = get_object_or_404(Trip, pk=pk)
    if request.method == 'POST':
        form = TripForm(request.POST, instance=trip)
        if form.is_valid():
            form.save()
            return redirect('trips:trip_details_page', pk=pk)
    else:
        form = TripForm(instance=trip)
    return render(request, 'edit_trip.html', {'form': form, 'trip': trip})

def delete_trip(request, pk):
    trip = get_object_or_404(Trip, pk=pk)
    if request.method == 'POST':
        trip.delete()
        return redirect('trips:trips_page')
    return render(request, 'delete_confirmation.html', {'trip': trip})

def add_trip_photos(request, pk):
    trip = get_object_or_404(Trip, pk=pk)

    if request.method == 'POST':
        if 'image' not in request.FILES:
            return JsonResponse({'success': False, 'message': 'The file is not getting to the server.'}, status=400)
        
        image = request.FILES['image']
        response_data = []

        try:
            if image.size > 5 * 1024 * 1024:  # Limitar tamaño del archivo a 5MB
                raise ValidationError("El archivo es demasiado grande.")
            
            photo = Photo(image=image, trip=trip)  # Crea una nueva instancia de Photo
            photo.save()  # Guarda la foto en la base de datos
            response_data.append({
                'photo_url': photo.image.url,
                'success': True,
            })
            return JsonResponse(response_data, safe=False)
        except ValidationError as e:
            return JsonResponse({'success': False, 'message': str(e)}, status=400)
        except Exception as e:
            return JsonResponse({'success': False, 'message': 'Ocurrió un error al guardar las fotos.'}, status=500)
    else:
        return render(request, 'add_trip_photos.html', {'trip': trip})

def delete_trip_photo(request, photo_id):
    if request.method == 'DELETE':  # Solo permitir el método DELETE
        try:
            photo = get_object_or_404(Photo, pk=photo_id)
            photo_path = photo.image.path if photo.image else None

            photo.delete()

            if photo_path and os.path.exists(photo_path):
                os.remove(photo_path)
                return JsonResponse({'message': 'Photo and file deleted successfully'}, status=200)
            else:
                return JsonResponse({'message': 'Photo deleted, but file not found'}, status=200)
        except Exception as e:
            return JsonResponse({'error': f'An error occurred: {str(e)}'}, status=500)
    return JsonResponse({'error': 'Invalid request method'}, status=405)

coupleApp/trips/templates/add_trip_photos.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Añadir fotos del viaje{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <script src="{% static 'js/trips/add_trip_photos.js' %}" defer></script>
</head>
<body>
  <header class="header">
      <div class="logo-container">
          <a href="{% url 'core:home_page' %}">
            <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
          </a>
      </div>
      <div class="header-content">
          <h1>Añadir fotos del viaje</h1>
      </div>
  </header>
  <div class="header-bar">
    <div class="back-button-container">
      <a href="{% url 'trips:trip_details_page' pk=trip.pk %}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
    </div>
  </div>
  <div class="main-container">
    <main class="main-content">
      <form method="post" enctype="multipart/form-data" id="dataForm" class="new-form">
        {% csrf_token %}
        <input type="file" name="images" id="images" class="upload-images" accept=".png, .jpg, .jpeg, .gif, .bmp, .tiff, .heic" multiple>
        <button type="submit" id="uploadButton">Guardar fotos</button>
      </form>

      <div id="uploadProgressContainer" class="uploadProgressContainer"></div>
    </main>
  </div>

  <div class="pop-up" id="popup">
    <p id="popupMessage"></p>
    <button onclick="closePopup()">Cerrar</button>
  </div>

  <footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
  </footer>
</body>

coupleApp/trips/templates/edit_trip.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Editar viaje{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <script src="{% static 'js/trips/add_edit_trip.js' %}" defer></script>
</head>
<body>
  <header class="header">
      <div class="logo-container">
          <a href="{% url 'core:home_page' %}">
            <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
          </a>
      </div>
      <div class="header-content">
          <h1>Editar viaje a: {{ trip.destiny }}</h1>
      </div>
  </header>
  <div class="header-bar">
    <div class="back-button-container">
      <a href="{% url 'trips:trip_details_page' trip.pk %}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
    </div>
  </div>
  <div class="main-container">
    <main class="main-content">
      <form method="post" id="dataForm" class="new-form">
        {% csrf_token %}
            <!-- Campo de Nombre -->
        <div class="form-group">
          <label for="name">Nombre</label>
          <input type="text" id="name" name="name" class="form-control" value="{{ trip.destiny }}" required>
          <ul id="autocompleteSuggestions" class="autocomplete-suggestions"></ul>
        </div>
        
        <!-- Campo de Descripción -->
        <div class="form-group">
            <label for="description">Descripción</label>
            <textarea id="description" name="description" class="form-control">{{ trip.description }}</textarea>
        </div>
        
        <!-- Campo de Fecha de Inicio -->
        <div class="form-group">
            <label for="start_date">Fecha de inicio</label>
            <input type="date" id="start_date" name="start_date" class="form-control" value="{{ trip.start_date|date:'Y-m-d' }}" required>
        </div>
        
        <!-- Campo de Fecha de Fin -->
        <div class="form-group">
            <label for="end_date">Fecha de fin</label>
            <input type="date" id="end_date" name="end_date" class="form-control" value="{{ trip.end_date|date:'Y-m-d' }}" required>
        </div>
        
        <!-- Campo de Latitud -->
        <div class="form-group">
            <label for="latitude">Latitud</label>
            <input type="text" id="latitude" name="latitude" class="form-control" value="{{ trip.latitude }}" readonly>
        </div>
        
        <!-- Campo de Longitud -->
        <div class="form-group">
            <label for="longitude">Longitud</label>
            <input type="text" id="longitude" name="longitude" class="form-control" value="{{ trip.longitude }}" readonly>
        </div>
        
        <!-- Botón de Envío -->
        <button type="submit">Guardar cambios</button>
      </form>
    </main>
  </div>

  <footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
  </footer>
</body>
</html>

coupleApp/trips/templates/new_trip.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Añadir sitio{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <script src="{% static 'js/add_edit_trip.js' %}" defer></script>
</head>
<body>
  <header class="header">
      <div class="logo-container">
          <a href="{% url 'core:home_page' %}">
            <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
          </a>
      </div>
      <div class="header-content">
          <h1>Añadir un sitio nuevo</h1>
      </div>
  </header>
  <div class="main-container">
    <div class="back-button-container">
      <a href="{% url 'trips:trips_page' %}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
    </div>
    <main class="main-content">
      <form method="post" id="dataForm" class="new-trip-form">
        {% csrf_token %}
            <!-- Campo de Nombre -->
        <div class="form-group">
          <label for="destiny">Destino</label>
          <input type="text" id="destiny" name="destiny" class="form-control" placeholder="Escribe el nombre" required>
          <ul id="autocompleteSuggestions" class="autocomplete-suggestions"></ul>
        </div>
        
        <!-- Campo de Descripción -->
        <div class="form-group">
            <label for="description">Descripción</label>
            <textarea id="description" name="description" class="form-control" placeholder="Escribe una descripción"></textarea>
        </div>
        
        <!-- Campo de Fecha de Inicio -->
        <div class="form-group">
            <label for="start_date">Fecha de inicio</label>
            <input type="date" id="start_date" name="start_date" class="form-control" required>
        </div>
        
        <!-- Campo de Fecha de Fin -->
        <div class="form-group">
            <label for="end_date">Fecha de fin</label>
            <input type="date" id="end_date" name="end_date" class="form-control" required>
        </div>
        
        <!-- Campo de Latitud -->
        <div class="form-group">
            <label for="latitude">Latitud</label>
            <input type="text" id="latitude" name="latitude" class="form-control" readonly>
        </div>
        
        <!-- Campo de Longitud -->
        <div class="form-group">
            <label for="longitude">Longitud</label>
            <input type="text" id="longitude" name="longitude" class="form-control" readonly>
        </div>
        
        <!-- Botón de Envío -->
        <button type="submit" onclick="handleSubmit(event)">Guardar</button>
      </form>
    </main>
  </div>

  <div class="pop-up" id="popup">
    <p id="popupMessage"></p>
    <button onclick="closePopup()">Cerrar</button>
  </div>

  <footer class="footer">
    <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
  </footer>
</body>
  

coupleApp/trips/templates/trip_details_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}Detalles del viaje{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/trips/trip_details_page.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">

    <script src="{% static 'js/trips/trip_details_page.js' %}" defer></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Detalles del viaje</h1>
        </div>
    </header>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% url 'trips:trips_page' %}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">
            <div class="details">
                <header class="details-header">
                    <div class="action-buttons">
                        <a href="{% url 'trips:edit_trip' trip.pk %}" class="btn-edit"><i class="fas fa-pencil-alt"></i></a>
                        <form action="{% url 'trips:delete_trip' trip.pk %}" method="post" class="btn-delete-form">
                            {% csrf_token %}
                            <button type="submit" class="btn-delete" onclick="return confirm('¿Estás seguro de que deseas eliminar este sitio?')"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </div>
                    <h2>{{ trip.destiny }}</h2>
                    <p class="date">
                        <strong>Fecha:</strong> 
                        {{ trip.start_date|date:"d M Y" }} - {{ trip.end_date|date:"d M Y" }}
                    </p>
                </header>
        
                <section class="description">
                    <h3>Descripción</h3>
                    <p>{{ trip.description }}</p>
                </section>
        
                <section class="photos">
                    <h3>Fotos del Viaje</h3>
                    {% if trip.photos.all %}
                        <div class="photos-gallery">
                            {% for photo in trip.photos.all %}
                                <div class="photo-card">
                                    <img src="/media/{{ photo.image }}" alt="Foto de {{ trip.destiny }}" class="trip-photo" onclick="openModal('/media/{{ photo.image }}', '{{ forloop.counter0 }}', '{{photo.id}}')">
                                </div>
                            {% endfor %}
                        </div>
                        <div id="photo-modal" class="photo-modal">
                            <div class="modal-header">
                                <button class="btn-download" onclick="downloadImage()"><i class="fas fa-download"></i></button>
                                <button class="btn-delete" onclick="deleteImage('{{ trip.pk }}', '{{ photo.id }}')"><i class="fas fa-trash-alt"></i></button>
                                <span class="close" onclick="closeModal()">&times;</span>
                            </div>
                            <span class="nav-arrow left-arrow" onclick="navigateModal(-1)">&#10094;</span> <!-- Flecha izquierda -->
                            <span class="nav-arrow right-arrow" onclick="navigateModal(1)">&#10095;</span> <!-- Flecha derecha -->
                            <img class="modal-content" id="modal-image">
                        </div>

                        <div class="pop-up" id="popup">
                            <p id="popupMessage"></p>
                            <button onclick="closePopup('{{trip.pk}}')">Cerrar</button>
                        </div>
        
                        <div class="add-photo-container">
                            <a href="{% url 'trips:add_trip_photos' pk=trip.pk %}" class="btn-add-photo">
                                <button type="button">Añadir Foto</button>
                            </a>
                        </div>
                    {% else %}
                        <p>No hay fotos disponibles.</p>
                        <div class="add-photo-container">
                            <a href="{% url 'trips:add_trip_photos' pk=trip.pk %}" class="btn-add-photo">
                                <button type="button">Añadir Foto</button>
                            </a>
                        </div>
                    {% endif %}
                </section>
            </div>
        </main>
    </div>
    <footer class="footer">
        <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
    </footer>
</body>
</html>

coupleApp/trips/templates/trips_page.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Viajes{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/trips/trips_page.css' %}">
    <link rel="icon" href="{% static 'images/Lucier.ico' %}" type="image/x-icon">
    
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

    <script>
        const geojsonUrl = "{% url 'trips:trips_geojson' %}";
    </script>
    <script src="{% static 'js/trips/trips_page.js' %}" defer></script>
</head>
<body>
    <header class="header">
        <div class="logo-container">
            <a href="{% url 'core:home_page' %}">
                <img src="{% static 'images/Lucier.png' %}" alt="Logo Lucier" class="logo">
            </a>
        </div>
        <div class="header-content">
            <h1>Viajes</h1>
            <p>Aquí puedes ver todos los viajes que hemos hecho y añadir los nuevos que hagamos.</p>
        </div>
    </header>
    <div class="header-bar">
        <div class="back-button-container">
            <a href="{% url 'core:home_page' %}" class="btn-back" aria-label="Volver a la lista de sitios">&#8592;</a>
        </div>
        <div class="add-buttons-container">
            <div id="add-button-container" class="add-button-container">
                <a href="{% url 'trips:new_trip' %}" class="btn-add">
                    <button type="button">Añadir nuevo viaje</button>
                </a>
            </div>
        </div>
    </div>
    <div class="main-container">
        <main class="main-content">       
            <div class="trips-container-wrapper">
                <button id="left" class="scroll-btn left">&#8592;</button>
                <div class="trips-container">
                    {% for trip in trips %}
                    <div class="trip-card">
                        <a href="{% url 'trips:trip_details_page' pk=trip.pk %}">
                            <h2>{{ trip.destiny }}</h2>
                            <p>{{ trip.description }}</p>
                            <p><strong>Fechas:</strong> {{ trip.start_date|date:"j F Y" }} al {{ trip.end_date|date:"j F Y" }}</p>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <button id="right" class="scroll-btn right">&#8594;</button>
            </div>

            <div class="map-container">
                <div id="map"></div>
            </div>
        </main>
    </div>

    <footer class="footer">
        <p>&copy; 2024 Lucier <span style="color: #C71585;">❤</span></p>
    </footer>
</body>
</html>